apiVersion: v1
kind: Namespace
metadata:
    name: net-api-action-ns

---
apiVersion: v1
kind: Service
metadata:
  name: net-api-action-sv
  namespace: net-api-action-ns
spec:
  selector:
    app: net-api-action-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-api-action-deploy
  namespace: net-api-action-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-api-action-app
  template:
    metadata:
      labels:
        app: net-api-action-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: net-api-action-app
        image: demogithubaction.azurecr.io/net-api-action:v0.1.0
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: applicationUrl
          value: "http://*:80"
        ports:
        - containerPort: 80
          name: http